### PR TITLE
Mongodump 2.6 compatibility

### PR DESCRIPTION
**Pull request by singlow**
I am using mongo 2.6 and export was not working. I found 2 quick fixes that fixed 2.6.11 but did not break the default 3.x in my testing.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Mind fixing the test?

@Flink thoughts on this?

**Comment by Flink** [comment]
@josegonzalez Just tested and it works as intended. Indeed without this patch I had the same problem.

@singlow Could you squash your commits where you fix tests into the others? It would be perfect then :) (Your other commits are nicely written, that’s great!)

**Comment by singlow** [comment]
I have reduced it to the two real commits - amending the fixes and test modifications to their respective commits.

**Comment by Flink** [comment]
Nice!
@josegonzalez :+1: for me :)

**Pull request merged**
