### PR TITLE
Change default mongo version to 4.0.3

### PR DESCRIPTION
**Pull request by HmFlashy**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Is an upgrade from 3 to 4 safe?

**Comment by HmFlashy** [comment]
Yes, I did work with it just fine. It can have some compatibility issues with 3.X versions but people can still use 3.X versions with this plugin and they don't have to upgrade to this version.
I tried to put the environment variable to 4.0.3 on my local machine and dokku just created my mongo container just fine and I could use it like the previous releases.

**Comment by nwokolawrence6** [comment]
has this upgrade been done

**Comment by josegonzalez** [comment]
Closing as this was updated in #140.

**Pull request closed without merging**
